### ISSUE TITLE
MOSFET IRF820 son obsoletos, cambiar por FQT13N06L 

### ISSUE THREAD

**Issue by jcecconi** [ciaa/Hardware#44]
Actualmente existen MOSFET con mucha menor Rds (incluso con menor Vgs), menor Qg, menor disipación para igual ID, menor footprint,  etc...incluso a menor precio. Por lo tanto estuvimos viendo un poco lo disponible y encontramos los siguientes transistores (bajamos la Vds requerida a 60V aprox. porque la CIAA esta pensado para un tablero de 24V, no tiene sentido tener Vds de 500V)

Opcion para 60V: FQT13N06L

Opcion para 100V (alternativa 2): FDT86106LZ

La Rds en general pasó de 3 ohm a 100mOhm aprox. como dato más relevante y el footprint se redujo de D2PAK (TO-263) a SOT223

**Comment by pridolfi** [comment]
Done, closed.
