### ISSUE TITLE
Jumpers para terminaciones en RS485 / CAN mediante pines de .1

### ISSUE THREAD

**Issue by jcecconi** [ciaa/Hardware#47]
De esta manera se puede modificar en el campo, sin necesidad de tener un soldador!
Aquellos jumpers que no requieren modificación en el campo y que deben permanecer fijas, como por ejemplo una asignación de una GPIO para otra función, pueden realizarse con el puente de estaño

**Comment by pridolfi** [comment]
Done, closed.
